# Generated by Django 6.0.4 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_video_conversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
